version: "3.8"

services:
  frontend-nginx:
    image: word-games-nginx
    build:
      context: packages/frontend
    platform: linux/arm64/v8
    ports:
      - "12345:80"
  backend:
    image: word-games-backend
    build:
      context: packages/backend
    platform: linux/arm64/v8
    volumes:
      - word-games-backend-data:/data
    ports:
      - "12346:4000"
volumes:
  word-games-backend-data:
