version: "3.8"

services:
  frontend-nginx:
    image: word-games-nginx
    build:
      context: packages/frontend
    platform: linux/arm64/v8
    ports:
      - "12345:80"
    restart: unless-stopped

  backend:
    image: word-games-backend
    build:
      context: packages/backend
    platform: linux/arm64/v8
    # environment:
    #   - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - word-games-backend-data:/data
    ports:
      - "12346:4000"
    # restart: unless-stopped

volumes:
  word-games-backend-data:
